### ISSUE TITLE
Failed to connect to localhost, app crashing

### ISSUE THREAD

**Issue by theodoreapeters** [2Y2s1mple/xintent#3]
Upon launching app, xintent throws a toast warning saying "Failed to connect to localhost....."

Also any action causes the app to crash, although if the action was toggling one of the monitor settings, the new setting is shown when the app is opened again. 

Refer to attached screenshots
![Screenshot_2022-03-31-04-39-40](https://user-images.githubusercontent.com/32497269/161014193-da5f5d80-0ec1-4b27-abcb-29cfd7d96b4d.png)

When I toggle "Monitor startActivity" from On to Off, the app crashes. When I restart the app notice that "Monitor startActivity" is now Off, as expected. 
![Screenshot_2022-03-31-04-39-54](https://user-images.githubusercontent.com/32497269/161015202-586f1192-1012-461d-88ef-10a56d2cfdd4.png)

What causes the crash? Is monitor startActivity truly disabled/enabled after the crash? What's the significance of the connection failure toast warning message?

**Comment by 2Y2s1mple** [comment]
Sorry for the delay reply.

- What causes the crash? 
It depends. Maybe full logcat log would help to diagnose.

- Is monitor startActivity truly disabled/enabled after the crash?
Mostly, if there is ERROR toast, all functions is not working.

- What's the significance of the connection failure toast warning message?
It means the injected code is not running well.

ps:
Firstly, this apk is a kind of xposed-module, it relies on some *xposed-Framework to load it properly. 
(recommend [LSPosed/LSPosed: LSPosed Framework](https://github.com/LSPosed/LSPosed)
e.g:
![image](https://user-images.githubusercontent.com/11064144/196726507-8c47456c-5b6e-45b5-9d11-b85ff7615652.png)

**Comment by TheZ3ro** [comment]
I have the same error, this is logcat

```
D/SettingsActivity: handleMessage: SEND_KEYS = sA:false,gCP:true,sB:true,rR:true,sS:true,bS:true,sP:true,xlog:true,qI:true
I/SettingsActivity: SP_key='key_startActivity' SP_val='false'
E/AndroidRuntime: FATAL EXCEPTION: PREF_SEND_THREAD
    Process: com.zwk.xintent, PID: 9128
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintWriter.println(java.lang.String)' on a null object reference
        at com.zwk.xintent.ui.activity.SettingsActivity$2.handleMessage(SettingsActivity.java:92)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```


Edit: Ok, apparently the first time you install the module it cannot load and execute the `handleLoadPackage` function. After a first reboot then the module starts working 👍
